{
 "title": "k8s-☸-pgmon/cAdvisor-Brief",
 "tags": [
  "容器",
  "容器资源指标"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "容器正在使用的核心数",
   "type": "graph",
   "description": "container_cpu_usage_seconds_total -总和。在Kubernetes 1.9之前，会报告所有节点中的每个CPU。这在1.1.0中发生了变化",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[$Interval])) by (container_name,pod_name)",
     "legendFormat": "pod : {{ pod_name }} {{ container_name }}"
    }
   ]
  },
  {
   "title": "容器CPU受限时间",
   "type": "graph",
   "description": "与CPU极限计算饱和,随着定义了CPU使用率的上限。当容器超过其CPU限制时，Linux运行时将“限制”容器并记录它在系列中受限制的时间container_cpu_cfs_throttled_seconds_total。这是一个计数器再次跟踪每个容器，所以采取rate",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_cfs_throttled_seconds_total{image!=\"\"}[$Interval]))\r\nby (container_name,pod_name)",
     "legendFormat": "pod : {{ pod_name }} {{ container_name }}"
    }
   ]
  },
  {
   "title": "内存利用率",
   "type": "graph",
   "description": "我们需要排除名称中包含“POD”的容器。这是此容器的父cgroup，将跟踪窗格中所有容器的统计信息。\n\n你可能认为可以轻松跟踪内存利用率container_memory_usage_bytes，但是，此度量标准还包括可以在内存压力下逐出的缓存（思考文件系统缓存）项。更好的衡量标准是container_memory_working_set_bytes因为这是OOM正在关注的内容。",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate\n(container_memory_working_set_bytes{name!~\"POD\",container_name!=\"POD\",image!=\"\"}[$Interval]))\nby (name,container_name,pod_name)",
     "legendFormat": "{{ pod_name }} {{ container_name }}"
    }
   ]
  },
  {
   "title": "内存饱和度",
   "type": "graph",
   "description": "在这里，我们必须加入两个系列，一个来自cAdvisor，另一个来自kube-state-metrics。不幸的是，容器名称标签没有对齐，但PromQL对此有帮助label_join",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum\r\n(container_memory_working_set_bytes{image!=\"\",container_name!=\"POD\"}) by (container_name) / \r\nsum\r\n(label_join(kube_pod_container_resource_limits_memory_bytes,\"container_name\", \"\", \"container\")) \r\nby (container_name,pod_name)",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "磁盘I/O利用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total[5m])) by (container_name,device)",
     "legendFormat": "{{ container_name }}  writes"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total[5m])) by (container_name,device)",
     "legendFormat": "{{ container_name }}  reads"
    }
   ]
  },
  {
   "title": "Pod 接受的网络字节数",
   "type": "graph",
   "description": "容器级别的网络利用率，您可以选择以字节为单位测量，也可以选择发送和接收的数据包。这个查询有点不同，因为所有网络会计都发生在Pod级别，而不是容器！",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name}} "
    }
   ]
  },
  {
   "title": "Pod 累计的网络字节数",
   "type": "graph",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\"}[$Interval])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\"}[$Interval])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "接收时丢弃的数据包总数",
   "type": "graph",
   "description": "Cumulative count of packets dropped while receiving",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_packets_dropped_total{image!=\"\"}",
     "legendFormat": "{{ namespace }} {{ pod_name }}"
    }
   ]
  }
 ]
}