{
 "title": "k8s-☸-pgmon/Kubernetes API",
 "tags": [ "Kubernetes API" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "content": "- 请求率和延迟\r\n- 控制器工作队列的性能\r\n- Etcd helper 缓存工作队列和缓存性能"
  },
  {
   "title": "请求速率/5m",
   "type": "graph",
   "description": "这通过verb提供的所有kubernetes的5分钟的速率，其中包括所有的动作： WATCH, PUT, POST, PATCH, LIST, GET, DELETE, and CONNECT.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[5m])) by (resource, subresource, verb)",
     "legendFormat": "{{ resource}} {{ subresource }} {{ verb  }}"
    }
   ]
  },
  {
   "title": "http 5xx错误与请求率的比率",
   "type": "graph",
   "description": "HTTP服务器的错误跟踪为HTTP 5xx错误。使用此查询可以获得错误与请求率的比率",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_request_count{code=~\"^(?:5..)$\"}[5m]) / rate(apiserver_request_count[5m])",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "API响应分布",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(apiserver_request_latencies_bucket{subresource!=\"log\",verb!~\"^(?:CONNECT|WATCHLIST|WATCH|PROXY)$\"}) WITHOUT (instance, resource)) / 1e+06",
     "legendFormat": "{{ job }}{{ scope }} {{ verb }}"
    }
   ]
  },
  {
   "title": "API控制器工作队列的性能",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "APIServiceRegistrationController_adds",
     "legendFormat": "{{ instance }} {{ job }} workqueue 处理的添加总数:"
    },
    {
     "expr": "APIServiceRegistrationController_depth",
     "legendFormat": "{{ instance }} {{ job }}  当前工作深度："
    },
    {
     "expr": "APIServiceRegistrationController_queue_latency",
     "legendFormat": "{{ instance }} {{ job }}  {{ quantile }} 队列延迟分布"
    },
    {
     "expr": "APIServiceRegistrationController_queue_latency_count",
     "legendFormat": "{{ instance }} {{ job }}   队列延迟计数"
    },
    {
     "expr": "APIServiceRegistrationController_queue_latency_sum",
     "legendFormat": "{{ instance }} {{ job }}  队列延迟总和"
    },
    {
     "expr": "APIServiceRegistrationController_retries",
     "legendFormat": "{{ instance }} {{ job }}   工作队列处理的重试总次数"
    },
    {
     "expr": "APIServiceRegistrationController_work_duration",
     "legendFormat": "{{ instance }} {{ job }}  {{ quantile }} 处理所需时长"
    },
    {
     "expr": "APIServiceRegistrationController_work_duration_count",
     "legendFormat": "{{ instance }} {{ job }} 工作时间计数"
    },
    {
     "expr": "APIServiceRegistrationController_work_duration_sum",
     "legendFormat": "{{ instance }} {{ job }}  持续时间总和"
    }
   ]
  },
  {
   "title": "Etcd交互",
   "type": "graph",
   "description": "如果在一段时间内没有请求，则无法计算百分位数。在那种情况下报告NaN。",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "etcd_helper_cache_entry_count", "legendFormat": "{{ instance }} 缓存中的元素数" },
    { "expr": "etcd_helper_cache_hit_count", "legendFormat": "{{ instance }}  缓存命中数" },
    { "expr": "etcd_helper_cache_miss_count", "legendFormat": "{{ instance }}  缓存未命中数" },
    {
     "expr": "etcd_request_cache_add_latencies_summary_count",
     "legendFormat": "{{ instance }}  缓存添加数量"
    },
    {
     "expr": "etcd_request_cache_add_latencies_summary_sum ",
     "legendFormat": "{{ instance }}  将项目放入缓存所花费的总时间"
    },
    {
     "expr": "histogram_quantile(0.9,rate(etcd_request_cache_get_latencies_summary[5m]))"
    },
    {
     "expr": "etcd_request_cache_get_latencies_summary_count",
     "legendFormat": "{{ instance }} 缓存获取次数的计数"
    },
    {
     "expr": "etcd_request_cache_get_latencies_summary_sum",
     "legendFormat": "{{ instance }} 缓存中获取项目所花费的总时间"
    },
    {
     "expr": "sum(rate(etcd_request_cache_add_latencies_summary[5m])) by (instance,quantile)"
    },
    {
     "expr": "rate(etcd_request_cache_add_latencies_summary_sum[5m])  / rate(etcd_request_cache_add_latencies_summary_count[5m])"
    }
   ]
  }
 ]
}