{
 "title": "k8s-☸-pgmon/cAdvisor-namespace",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "namespace ",
  "容器",
  "资源状态"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "pgmon", "label": "pgmon", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "content": "- 参考 https://github.com/kubernetes/kube-state-metrics/tree/master/Documentation"
  },
  {
   "title": "configMap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "configMap",
     "type": "table",
     "gridPos": { "h": 5, "w": 15, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(kube_configmap_info) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "secret 计数",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "secret共计",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "sum(kube_secret_info)" }
     ]
    },
    {
     "title": "describe",
     "type": "table",
     "gridPos": { "h": 6, "w": 19, "x": 5, "y": 4 },
     "targets": [
      {
       "expr": "sum(kube_secret_type) by (namespace,secret,type)"
      }
     ]
    },
    {
     "title": "$namespace secre",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_secret_info{namespace=~\"^$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "全部名称空间",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_namespace_status_phase)"
      }
     ]
    },
    {
     "title": "Active名称空间数",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 5, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_namespace_status_phase{phase=\"Active\"})"
      }
     ]
    },
    {
     "title": "Terminating",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_namespace_status_phase{phase=\"Terminating\"})"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "max(kube_namespace_status_phase{phase=\"Active\"}) by (phase,namespace)"
      },
      {
       "expr": "sum(max(kube_namespace_status_phase{phase=\"Terminating\"}) by (phase,namespace))"
      }
     ]
    }
   ]
  },
  {
   "title": "service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "service status",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "max(kube_service_info) by (service,namespace,cluster_ip)"
      }
     ]
    }
   ]
  },
  {
   "title": "replicas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "ReplicaSet指标",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "max(kube_replicaset_status_replicas) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_status_fully_labeled_replicas) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_status_ready_replicas) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_status_observed_generation) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_spec_replicas) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_metadata_generation) by (replicaset,namespace)"
      },
      {
       "expr": "max(kube_replicaset_created) by (replicaset,namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 10, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "总内存大小",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "$namespace容器占用比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\",namespace=\"$namespace\"})",
     "legendFormat": "{{ $namespace 占用 }} /个"
    },
    {
     "expr": "count(container_last_seen{image!=\"\"})",
     "legendFormat": "总容器 /个"
    }
   ]
  },
  {
   "title": "$namespace内存占用比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",namespace=\"$namespace\"})/1024/1024",
     "legendFormat": "{{ $namespace }} 使用的内存大小"
    },
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024",
     "legendFormat": "容器共使用内存大小 / KB"
    }
   ]
  },
  {
   "title": "$namespace cpu比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",namespace=\"$namespace\"}[5m]) * 100)",
     "legendFormat": "$namespace 使用的CPU"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)",
     "legendFormat": "容器共使用的CPU"
    }
   ]
  },
  {
   "title": "CPU总核心数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode =\"system\"}) by (node)"
    }
   ]
  },
  {
   "title": "kube_pod_status_phase Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "kube_pod_status_phase have failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "$namespace Num",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\",namespace=\"$namespace\"})",
     "legendFormat": "{{ $namespace }}"
    },
    {}
   ]
  },
  {
   "title": "$namespace Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 14 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",namespace=\"$namespace\"})/1024/1024"
    }
   ]
  },
  {
   "title": "$namespace Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",namespace=\"$namespace\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",namespace=~\"^$namespace\",name=~\"^k8s_.*\"}[$interval])) by (pod_name) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"^$namespace\"}[$interval])) by (container_name, pod_name)",
     "legendFormat": "pod: {{pod_name}} {{ container_name }}"
    }
   ]
  },
  {
   "title": "Pod Network  I/O 5分钟",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",namespace=~\"^$namespace\",name=~\"^k8s_.*\"}[$interval])) by (pod_name)",
     "legendFormat": "->{{pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",namespace=~\"^$namespace\",name=~\"^k8s_.*\"}[$interval])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}