{
 "title": "k8s-☸-pgmon/cAdvisor-namespace",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "namespace ",
  "容器",
  "资源状态"
 ],
 "time": { "from": "2019-01-16T07:34:18.385Z", "to": "2019-01-16T07:54:18.385Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_namespace_status_phase,namespace)"
   }
  ]
 },
 "panels": [
  { "title": "deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "总内存大小",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "$namespace容器占用比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\",namespace=\"$namespace\"})",
     "legendFormat": "{{ $namespace 占用 }} /个"
    },
    {
     "expr": "count(container_last_seen{image!=\"\"})",
     "legendFormat": "总容器 /个"
    }
   ]
  },
  {
   "title": "$namespace内存占用比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",namespace=\"$namespace\"})/1024/1024",
     "legendFormat": "{{ $namespace }} 使用的内存大小"
    },
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024",
     "legendFormat": "容器共使用内存大小 / KB"
    }
   ]
  },
  {
   "title": "$namespace cpu比例",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",namespace=\"$namespace\"}[5m]) * 100)",
     "legendFormat": "$namespace 使用的CPU"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)",
     "legendFormat": "容器共使用的CPU"
    }
   ]
  },
  {
   "title": "CPU总核心数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode =\"system\"}) by (node)"
    }
   ]
  },
  {
   "title": "kube_pod_status_phase Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "kube_pod_status_phase have failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "$namespace Num",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\",namespace=\"$namespace\"})",
     "legendFormat": "{{ $namespace }}"
    },
    {}
   ]
  },
  {
   "title": "$namespace Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",namespace=\"$namespace\"})/1024/1024"
    }
   ]
  },
  {
   "title": "$namespace Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",namespace=\"$namespace\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",namespace=\"$namespace\",name=~\"^k8s_.*\"}[$interval])) by (pod_name) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=\"$namespace\"}[$interval])) by (container_name, pod_name)",
     "legendFormat": "pod: {{pod_name}} {{ container_name }}"
    }
   ]
  },
  {
   "title": "Pod Network  I/O 5分钟",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",namespace=\"$namespace\",name=~\"^k8s_.*\"}[$interval])) by (pod_name)",
     "legendFormat": "->{{pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",namespace=\"$namespace\",name=~\"^k8s_.*\"}[$interval])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}